### ISSUE TITLE
0.17.46 will not load this mod

### ISSUE THREAD

**Issue by billbo99** [Nexela/PickerAtheneum#1]
24.509 Mods to disable:Failed to load mods: Error while loading entity prototype "picker-pointer-beam" (beam): Beam animation frame count mismatch. start_light (16) must have same number of frames as tail (1).
Modifications: Picker Atheneum [core]

Mods to be disabled:
• PickerAtheneum

**Comment by wchristian** [comment]
I've created a tentative fix in #2
